/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_testcrud;

import com.sun.istack.internal.logging.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import sun.util.logging.PlatformLogger;
/**
 *
 * @author dhenarra
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        selectData();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlTanggal = new javax.swing.JLabel();
        jlJam = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbSave = new javax.swing.JButton();
        jbEdit = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jbRefresh = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtSiswa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfNis = new javax.swing.JTextField();
        jtfNama = new javax.swing.JTextField();
        jrbLK = new javax.swing.JRadioButton();
        jrbPR = new javax.swing.JRadioButton();
        jtfKelas = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAlamat = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jdcTL = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtSiswa1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));
        jPanel6.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("The Real Informatics School");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(118, 30, 510, 30);

        jlTanggal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jlTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jlTanggal.setText("Tanggal");
        jPanel6.add(jlTanggal);
        jlTanggal.setBounds(650, 40, 100, 20);

        jlJam.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jlJam.setForeground(new java.awt.Color(255, 255, 255));
        jlJam.setText("Jam");
        jPanel6.add(jlJam);
        jlJam.setBounds(650, 64, 100, 20);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FORM PENDAFTARAN SMK TELKOM MALANG");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(116, 5, 518, 31);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 790, 100);

        jPanel2.setBackground(new java.awt.Color(198, 40, 40));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ISI BIODATA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 190, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 250, 50);

        jPanel4.setBackground(new java.awt.Color(198, 40, 40));
        jPanel4.setLayout(null);

        jbSave.setBackground(new java.awt.Color(229, 57, 53));
        jbSave.setForeground(new java.awt.Color(255, 255, 255));
        jbSave.setText("Save");
        jbSave.setBorderPainted(false);
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jPanel4.add(jbSave);
        jbSave.setBounds(20, 10, 70, 30);

        jbEdit.setBackground(new java.awt.Color(229, 57, 53));
        jbEdit.setForeground(new java.awt.Color(255, 255, 255));
        jbEdit.setText("Edit");
        jbEdit.setBorderPainted(false);
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });
        jPanel4.add(jbEdit);
        jbEdit.setBounds(340, 10, 70, 30);

        jbDelete.setBackground(new java.awt.Color(229, 57, 53));
        jbDelete.setForeground(new java.awt.Color(255, 255, 255));
        jbDelete.setText("Delete");
        jbDelete.setBorderPainted(false);
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbDelete);
        jbDelete.setBounds(100, 10, 70, 30);

        jbClear.setBackground(new java.awt.Color(229, 57, 53));
        jbClear.setForeground(new java.awt.Color(255, 255, 255));
        jbClear.setText("Clear");
        jbClear.setBorderPainted(false);
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });
        jPanel4.add(jbClear);
        jbClear.setBounds(180, 10, 70, 30);

        jbRefresh.setBackground(new java.awt.Color(229, 57, 53));
        jbRefresh.setForeground(new java.awt.Color(255, 255, 255));
        jbRefresh.setText("Refresh");
        jbRefresh.setBorderPainted(false);
        jbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshActionPerformed(evt);
            }
        });
        jPanel4.add(jbRefresh);
        jbRefresh.setBounds(260, 10, 70, 30);

        jbPrint.setBackground(new java.awt.Color(229, 57, 53));
        jbPrint.setForeground(new java.awt.Color(255, 255, 255));
        jbPrint.setText("Print");
        jbPrint.setBorderPainted(false);
        jbPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrintActionPerformed(evt);
            }
        });
        jPanel4.add(jbPrint);
        jbPrint.setBounds(420, 10, 70, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(250, 100, 540, 50);

        jtSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Tanggal Lahir", "Kelas", "Email", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtSiswa);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 160, 530, 380);

        jPanel3.setBackground(new java.awt.Color(229, 57, 53));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIS");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 10, 100, 20);
        jPanel3.add(jtfNis);
        jtfNis.setBounds(10, 30, 220, 30);
        jPanel3.add(jtfNama);
        jtfNama.setBounds(10, 80, 220, 30);

        buttonGroup1.add(jrbLK);
        jrbLK.setText("laki-laki");
        jPanel3.add(jrbLK);
        jrbLK.setBounds(10, 130, 80, 23);

        buttonGroup1.add(jrbPR);
        jrbPR.setText("perempuan");
        jPanel3.add(jrbPR);
        jrbPR.setBounds(100, 130, 100, 23);
        jPanel3.add(jtfKelas);
        jtfKelas.setBounds(10, 230, 220, 30);
        jPanel3.add(jtfEmail);
        jtfEmail.setBounds(10, 280, 220, 30);

        jtaAlamat.setColumns(20);
        jtaAlamat.setRows(5);
        jScrollPane1.setViewportView(jtaAlamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 220, 60);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Alamat Asal");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 310, 100, 20);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nama");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 60, 100, 20);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jenis Kelamin");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 110, 100, 20);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tanggal Lahir");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 160, 100, 20);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 260, 100, 20);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Kelas");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 210, 100, 20);
        jPanel3.add(jdcTL);
        jdcTL.setBounds(10, 180, 220, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 150, 240, 400);

        jPanel5.setBackground(new java.awt.Color(229, 57, 53));
        jPanel5.setLayout(null);

        jtSiswa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtSiswa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtSiswa1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtSiswa1);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 530, 330);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(240, 150, 550, 400);

        setBounds(0, 0, 806, 588);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(jdcTL.getDate());
        
        if ("".equals(jtfNis.getText()) || "".equals(jtaAlamat.getText()) || "".equals(jtfKelas.getText()) || tanggal.equals("") || "".equals(jtfNama.getText()) || "".equals(jtfEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (jrbLK.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "INSERT INTO t_siswa (NIS,NamaSiswa,TanggalLahir,JenisKelamin,Kelas,Email,Alamat) "
                    + "VALUES('" + jtfNis.getText() + "','" + jtfNama.getText() + "','" + tanggal + "','" + JK + "','"
                    + jtfKelas.getText() + "','" +jtfEmail.getText() + "','" + jtaAlamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(jdcTL.getDate());
        if ("".equals(jtfNis.getText()) || "".equals(jtaAlamat.getText()) || "".equals(jtfKelas.getText()) || "".equals(jtfNama.getText()) || "".equals(jtfEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String JK = "";
            if (jrbLK.isSelected()) {
                JK = "L";
            } else {
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET "
                    + "NamaSiswa='"+jtfNama.getText()+"',"+"TanggalLahir='" + tanggal + "',"+"JenisKelamin='" + JK + "',"
                    + "Kelas='"+jtfKelas.getText()+"',"+"Email='" + jtfEmail.getText() + "',"
                    + "Alamat='" + jtaAlamat.getText()+"' "
                    + "WHERE NIS='"+jtfNis.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbEditActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        // TODO add your handling code here:
       int baris = jtSiswa.getSelectedRow();
        if (baris != -1) {
            String NIS = jtSiswa.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
        jtfNis.setText("");
        jtfNama.setText("");
        jtfKelas.setText("");
        jtfEmail.setText("");
        jtaAlamat.setText("");
        jdcTL.setDate(null);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jbClearActionPerformed

    private void jbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jbRefreshActionPerformed

    private void jtSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSiswaMouseClicked
        // TODO add your handling code here:
        int baris = jtSiswa.getSelectedRow();
        if (baris != -1) {
            jtfNis.setText(jtSiswa.getValueAt(baris, 0).toString());
            jtfNama.setText(jtSiswa.getValueAt(baris, 1).toString());
            if ("Laki-laki".equals(jtSiswa.getValueAt(baris, 3).toString())) {
                jrbLK.setSelected(true);
            } else {
                jrbPR.setSelected(true);
            }
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try
            {
                dateFormat = date.parse(jtSiswa.getValueAt(baris,2).toString());
            }catch(ParseException ex)
            {}
            jtfKelas.setText(jtSiswa.getValueAt(baris, 4).toString());
            jtfEmail.setText(jtSiswa.getValueAt(baris, 5).toString());
            jtaAlamat.setText(jtSiswa.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_jtSiswaMouseClicked

    private void jtSiswa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtSiswa1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtSiswa1MouseClicked

    private void jbPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)   ");
        try
        {
            jtSiswa.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print $s$n", e.getMessage());
        }
    }//GEN-LAST:event_jbPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbRefresh;
    private javax.swing.JButton jbSave;
    private com.toedter.calendar.JDateChooser jdcTL;
    private javax.swing.JLabel jlJam;
    private javax.swing.JLabel jlTanggal;
    private javax.swing.JRadioButton jrbLK;
    private javax.swing.JRadioButton jrbPR;
    private javax.swing.JTable jtSiswa;
    private javax.swing.JTable jtSiswa1;
    private javax.swing.JTextArea jtaAlamat;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfKelas;
    private javax.swing.JTextField jtfNama;
    private javax.swing.JTextField jtfNis;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NIS","Nama Siswa","Tanggal Lahir","Jenis Kelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NIS = rs.getString(1);
                String namaSiswa = rs.getString(2);
                String jenisKelamin = "";
                if ("L".equals(rs.getString(4))) {
                    jenisKelamin = "Laki-laki";
                } else {
                    jenisKelamin = "Perempuan";
                }
                String tanggal =rs.getString(3);
                String kelas = rs.getString(5);
                String email = rs.getString(6);
                String alamat = rs.getString(7);
                String data[] = {NIS,namaSiswa,tanggal,jenisKelamin,kelas,email,alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtSiswa.setModel(dtm);
    }
    public void setTanggal()
    {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        jlTanggal.setText(kal.format(skrg));
    }
    public void setJam()
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                if(nilai_jam<=9)
                {
                    nol_jam="0";
                }
                if(nilai_menit<=9)
                {
                    nol_menit="0";
                }
                if(nilai_detik<=9)
                {
                    nol_detik="0";
                }
                String jam = nol_jam+Integer.toString(nilai_jam);
                String menit = nol_menit+Integer.toString(nilai_menit);
                String detik = nol_detik+Integer.toString(nilai_detik);
                jlJam.setText(jam+":"+menit+":"+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
}
